import Head from 'next/head'
import { useEffect, useState } from 'react';
export default function Home() {
  const [respuesta, setRespuesta] = useState([])
  const activar = async () => {
    const response = await fetch("/api/hello", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });

    const data = await response.json();
    setRespuesta(data)
    if (response.status !== 200) {
      throw data.error || new Error(`Request failed with status ${response.status}`);
    }
  }
  useEffect(() => {
    activar()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <table>
          <thead>
            <tr>
              <th>Id</th>
              <th>Nombre</th>
            </tr>
          </thead>
          <tbody>
            {respuesta.map((row) => (
              <tr>
                <td>{row.Id}</td>
                <td>{row.Nombre}</td>
              </tr>
            ))}
          </tbody>
        </table>

      </div>
    </>
  )
}
