import Head from 'next/head'
import { useEffect, useState } from 'react';
import LineChart from './lineChart';

export default function Home() {
  const [labl, setLabl] = useState([])
  const [valores, setValores] = useState([])
  const [data, setData] = useState({
    labels: [],
    datasets: [
      {
        label: 'Data',
        data: [],
        fill: false,
        borderColor: 'rgb(75, 192, 192)',
        tension: 0.1,
      },
    ],
  });
  const [contador, setContador] = useState(0)
  const [seconds, setSeconds] = useState(0);
  const [grafica, setGrafica] = useState();

  useEffect(() => {
    const timer = setInterval(() => {
      setSeconds((prevSeconds) => prevSeconds + 1);
    }, 1000);
    return () => clearInterval(timer);
  }, []);


  const activar = async () => {
    const response = await fetch("/api/hello", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });

    const data2 = await response.json();

    let newData = {}
    if (labl.length > 0) {
      console.log("entro")
      newData = {
        labels: [...labl, contador],
        datasets: [
          {
            ...data.datasets[0],
            data: [...data.datasets[0].data, data2.length],
          },
        ],
      };
    }else{
      newData = {
        labels: [contador],
        datasets: [
          {
            ...data.datasets[0],
            data: [data2.length],
          },
        ],
      };
    }

    setData(newData);
    setValores([...valores, data2.length])
    setLabl([...labl, contador])
    setContador(contador + 1)
    if (response.status !== 200) {
      throw data.error || new Error(`Request failed with status ${response.status}`);
    }
  }

  useEffect(() => {
    activar()
  }, [seconds])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className='flexear centrar'>Cantidad de datos en el tiempo</h1>
        <div className='altura'><LineChart valores={valores} etiquetas={labl} /></div>
      </div>
    </>
  )
}
